### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by JacobChrist** [Gooost/Ymodem-IAP#1]
Hello,

Did you write the C# Ymodem-IAP?  If so can you please add a license (MIT, BSD 3-Clause or Apache)?  If you did not can you point me to the original developer?  I also see this repo that looks very similar:

https://github.com/Chen-Guihui/Ymodem-IAP

Thanks

**Comment by Gooost** [comment]
嗨：


忘记在谁那边克隆了，大概率是

https://github.com/Chen-Guihui/Ymodem-IAP



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gooost/Ymodem-IAP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月16日(星期天) 凌晨0:58
收件人:&nbsp;"Gooost/Ymodem-IAP"<Ymodem-IAP@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Gooost/Ymodem-IAP] Licensing (#1)





 
Hello,
 
Did you write the C# Ymodem-IAP?  If so can you please add a license (MIT, BSD 3-Clause or Apache)?  If you did not can you point me to the original developer?  I also see this repo that looks very similar:
 
https://github.com/Chen-Guihui/Ymodem-IAP
 
Thanks

**Comment by JacobChrist** [comment]
Thank you!


谢谢

Jacob
